### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by chmorgan** [amarjanica/react-native-skia-expo-demo#1]
Without your repository and writeup I would have likely never gotten skia working here with expo. Thank you for documenting this.

I'm using expo 51.xx here on macOS.

Some things that surprised me:

* Following the RN skia instructions didn't work...
* The RN skia instructions are not at all clear how to support *both* web and mobile.
* Having to introduce the use of expo-router (I already use react navigation but the fact that the install steps don't consider the user might NOT be using expo-router) doesn't seem necessary but I'd have zero idea at this point how to do it otherwise, I'm new to this stuff.
* There is no mention in the skia instructions regarding the errors about the canvaskit usage of fs fixed by path-fs-canvaskit-postinstall.js. It was clear that the wasm shouldn't be using fs etc but no google hits made the fix particularly clear. (this fixed the canvaskit missing fs error)
* Having to add the metro configuration (this fixed the undefined Matrix error)

Wish this was easier and better documented but after several hours your repo here got me through it.

**Comment by amarjanica** [comment]
@chmorgan, you're welcome :)
Everything you mentioned, I've stumbled on these issues too...
That's why I thought it would be useful to sum it all up in an mvp example.
